### ISSUE TITLE
Gambling in tests

### ISSUE THREAD

**Issue by reod** [Schibsted-Tech-Polska/good-guy-http#6]
When I run tests, they pass not every time:
Fail scenario:

```
remek-mac:good-guy-http remigiuszambroziak$ npm test

> good-guy-http@1.7.2 test /Users/remigiuszambroziak/Documents/schibsted-tech-polska/good-guy-http
> ./node_modules/mocha/bin/mocha --recursive



  Caching
    ✓ should cache with the correct time-to-live (96ms)
    ✓ should respect must-revalidate
    ✓ should respect global 'allowServingStale' setting
    ✓ should respect no-cache
    ✓ should cope with caching errors
    ✓ should cope with slow caches by collapsing cache requests
    ✓ should not send multiple cache store requests for concurrent requests to the same URL (48ms)
    ✓ should cope with slow caches without making fetches incredibly long
    ✓ should respect the cache response timeout set
    ✓ should let the user force the caching settings
    ✓ should differentiate between requests with different Accept
    ✓ should cache 4xx errors by default
    ✓ should make it possible to turn off 4xx caching

  Callback interface
    ✓ should report successes correctly
    ✓ should report errors correctly
    ✓ should work with convenience methods

  Circuit breaking
    ✓ should kick in after enough requests fail with a 5xx error (146ms)
    ✓ should use separate breakers for different hosts (135ms)
    ✓ should be possible to turn off (118ms)

  Requests with collapsing
    ✓ should collapse identical requests by default
    1) shouldn't collapse even slightly different requests
    ✓ shouldn't collapse when explicitly turned off
    ✓ should make new requests if there is no ongoing request

  Convenience methods
    ✓ should use correct HTTP methods for requests

  Use different Promise library
    ✓ should use built-in Promises, if available
    ✓ should use custom constructor, if provided

  Non-idempotent requests
    ✓ should not be cached
    ✓ should not be retried
    ✓ should not be collapsed

  Postprocessing
    ✓ should work for uncached requests
    ✓ should work for cached requests with stale responses on (58ms)
    ✓ should work for cached requests with stale responses off
    ✓ should run only once for a set of collapsed requests

  Reconfiguration
    ✓ should be possible for good guy parameters
    ✓ should be possible for request parameters
    ✓ should be possible via the request

  Request lib
    ✓ should be taken from config, if provided

  Requesting with retries
    ✓ shouldn't break requests that succeed immediately
    ✓ should succeed if one of the retries succeeds
    ✓ should fail with the last error if we run out of retries
    ✓ should not retry if the response was a 4xx

  Good guy HTTP
    ✓ should resolve with a response on success
    ✓ should provide correct headers
    ✓ should reject the promise on 4xx HTTP status
    ✓ should reject the promise on 5xx HTTP status
    ✓ should reject when the request times out
    ✓ should reject when connection fails

  Cache settings parser
    ✓ should obey Cache-Control: no-cache
    ✓ should obey Cache-Control: no-store
    ✓ should obey Cache-Control: max-age
    ✓ should obey Cache-Control: must-revalidate
    ✓ should return undefined if it doesn't parse anything

  Canonicalization of requests
    ✓ should turn strings to objects
    ✓ should provide method and headers if missing
    ✓ should turn headers lowercase

  Functions wrapped with a circuit breaker
    ✓ should pass arguments and successes along
    ✓ should pass failures along
    ✓ should start returning CircuitBrokenError after enough failures
    ✓ should allow for multiple circuit breakers using a key function

  isIdempotent()
    ✓ should report true for read-only HTTP methods
    ✓ should report false for non-idempotent and mutating HTTP methods

  LRUCache
    ✓ should be able to store and retrieve elements
    ✓ should store values rather than references to elements
    ✓ should return values rather than references to elements
    ✓ should throw away oldest element when nothing is retrieved
    ✓ should throw away least recently used element when out of space

  Retrying promises
    ✓ should pass arguments and result on correctly
    ✓ should retry the right number of times
    ✓ should reject with the last error if retries are exhausted
    ✓ should not retry when the error has an 'unretriable' flag set

  Collapsing promises
    ✓ should pass arguments and result correctly
    ✓ should pass errors correctly
    ✓ should collapse multiple calls into one
    ✓ should collapse only when parameters are the same by default
    ✓ should make a new promise once the previous finishes
    ✓ should use the provide key function to check if calls should be collapsed

  Timeout wrapper for promises
    ✓ should pass results correctly
    ✓ should pass errors correctly
    ✓ should return timeouts as errors

  Promised requests
    ✓ should return the body on success
    ✓ should reject on 4xx HTTP status without the possibility of retrying
    ✓ should reject on 5xx HTTP status with possibility of retrying
    ✓ should reject when the request times out
    ✓ should reject when connection fails
    ✓ should include the request and response in HTTP errors
    ✓ should include the request in connectivity errors
    ✓ should add request info to error messages
    ✓ should respect the maximum response size

  Request keys
    ✓ should be generated correctly for string requests
    ✓ should be generated correctly for object requests
    ✓ should handle the 'qs' parameter correctly
    ✓ should include accept header if provided
    ✓ should work when request is wrapped in an array

  Response object
    ✓ should have a string representation looking like a HTTP response


  93 passing (1s)
  1 failing

  1) Requests with collapsing shouldn't collapse even slightly different requests:

      AssertionError: [ '3', '4' ] deepEqual [ '1', '2' ]
      + expected - actual

       [
      -  "3"
      -  "4"
      +  "1"
      +  "2"
       ]

      at test/top-to-bottom/collapsing-requests-test.js:33:14
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:497:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:555:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:600:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:683:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:624:18)
      at PromiseArray._resolve (node_modules/bluebird/js/release/promise_array.js:125:19)
      at PromiseArray._promiseFulfilled (node_modules/bluebird/js/release/promise_array.js:143:14)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:560:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:600:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:683:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:125:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:135:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:16:14)



npm ERR! Test failed.  See above for more details.
```

Success scenario:

```
remek-mac:good-guy-http remigiuszambroziak$ npm test

> good-guy-http@1.7.2 test /Users/remigiuszambroziak/Documents/schibsted-tech-polska/good-guy-http
> ./node_modules/mocha/bin/mocha --recursive



  Caching
    ✓ should cache with the correct time-to-live (98ms)
    ✓ should respect must-revalidate
    ✓ should respect global 'allowServingStale' setting
    ✓ should respect no-cache
    ✓ should cope with caching errors
    ✓ should cope with slow caches by collapsing cache requests
    ✓ should not send multiple cache store requests for concurrent requests to the same URL (43ms)
    ✓ should cope with slow caches without making fetches incredibly long
    ✓ should respect the cache response timeout set
    ✓ should let the user force the caching settings
    ✓ should differentiate between requests with different Accept
    ✓ should cache 4xx errors by default
    ✓ should make it possible to turn off 4xx caching

  Callback interface
    ✓ should report successes correctly
    ✓ should report errors correctly
    ✓ should work with convenience methods

  Circuit breaking
    ✓ should kick in after enough requests fail with a 5xx error (152ms)
    ✓ should use separate breakers for different hosts (146ms)
    ✓ should be possible to turn off (119ms)

  Requests with collapsing
    ✓ should collapse identical requests by default
    ✓ shouldn't collapse even slightly different requests
    ✓ shouldn't collapse when explicitly turned off
    ✓ should make new requests if there is no ongoing request (41ms)

  Convenience methods
    ✓ should use correct HTTP methods for requests

  Use different Promise library
    ✓ should use built-in Promises, if available
    ✓ should use custom constructor, if provided

  Non-idempotent requests
    ✓ should not be cached
    ✓ should not be retried
    ✓ should not be collapsed

  Postprocessing
    ✓ should work for uncached requests
    ✓ should work for cached requests with stale responses on (61ms)
    ✓ should work for cached requests with stale responses off
    ✓ should run only once for a set of collapsed requests

  Reconfiguration
    ✓ should be possible for good guy parameters
    ✓ should be possible for request parameters
    ✓ should be possible via the request

  Request lib
    ✓ should be taken from config, if provided

  Requesting with retries
    ✓ shouldn't break requests that succeed immediately
    ✓ should succeed if one of the retries succeeds
    ✓ should fail with the last error if we run out of retries
    ✓ should not retry if the response was a 4xx

  Good guy HTTP
    ✓ should resolve with a response on success
    ✓ should provide correct headers
    ✓ should reject the promise on 4xx HTTP status
    ✓ should reject the promise on 5xx HTTP status
    ✓ should reject when the request times out
    ✓ should reject when connection fails

  Cache settings parser
    ✓ should obey Cache-Control: no-cache
    ✓ should obey Cache-Control: no-store
    ✓ should obey Cache-Control: max-age
    ✓ should obey Cache-Control: must-revalidate
    ✓ should return undefined if it doesn't parse anything

  Canonicalization of requests
    ✓ should turn strings to objects
    ✓ should provide method and headers if missing
    ✓ should turn headers lowercase

  Functions wrapped with a circuit breaker
    ✓ should pass arguments and successes along
    ✓ should pass failures along
    ✓ should start returning CircuitBrokenError after enough failures
    ✓ should allow for multiple circuit breakers using a key function

  isIdempotent()
    ✓ should report true for read-only HTTP methods
    ✓ should report false for non-idempotent and mutating HTTP methods

  LRUCache
    ✓ should be able to store and retrieve elements
    ✓ should store values rather than references to elements
    ✓ should return values rather than references to elements
    ✓ should throw away oldest element when nothing is retrieved
    ✓ should throw away least recently used element when out of space

  Retrying promises
    ✓ should pass arguments and result on correctly
    ✓ should retry the right number of times
    ✓ should reject with the last error if retries are exhausted
    ✓ should not retry when the error has an 'unretriable' flag set

  Collapsing promises
    ✓ should pass arguments and result correctly
    ✓ should pass errors correctly
    ✓ should collapse multiple calls into one
    ✓ should collapse only when parameters are the same by default
    ✓ should make a new promise once the previous finishes
    ✓ should use the provide key function to check if calls should be collapsed

  Timeout wrapper for promises
    ✓ should pass results correctly
    ✓ should pass errors correctly
    ✓ should return timeouts as errors

  Promised requests
    ✓ should return the body on success
    ✓ should reject on 4xx HTTP status without the possibility of retrying
    ✓ should reject on 5xx HTTP status with possibility of retrying
    ✓ should reject when the request times out
    ✓ should reject when connection fails
    ✓ should include the request and response in HTTP errors
    ✓ should include the request in connectivity errors
    ✓ should add request info to error messages
    ✓ should respect the maximum response size

  Request keys
    ✓ should be generated correctly for string requests
    ✓ should be generated correctly for object requests
    ✓ should handle the 'qs' parameter correctly
    ✓ should include accept header if provided
    ✓ should work when request is wrapped in an array

  Response object
    ✓ should have a string representation looking like a HTTP response


  94 passing (1s)
```

Testing environment:

```
remek-mac:good-guy-http remigiuszambroziak$ node -v
v6.2.0
```

```
  Model Name:   MacBook Pro
  Model Identifier: MacBookPro11,4
  Processor Name:   Intel Core i7
  Processor Speed:  2,2 GHz
  Number of Processors: 1
  Total Number of Cores:    4
  L2 Cache (per Core):  256 KB
  L3 Cache: 6 MB
  Memory:   16 GB
```

**Comment by kjarmicki** [comment]
Hi, thanks for the report

I see that faulty test depends on setTimeout accuracy a bit more than it should. I've been able to reproduce issue locally and resolve it, but it's still [highly dependent on machine and OS](http://ejohn.org/blog/how-javascript-timers-work/).
Anyway, 50ms should be enough room for inacurracy without slowing down test suite too much, please pull the latest changes and check it out on your machine.

**Comment by kjarmicki** [comment]
ping @reod :) Could you pull this last commit and check if problem still occurs?

**Comment by reod** [comment]
I ran `npm test` 10 times in a row and everything went fine. Seems fixed for me.

**Comment by kjarmicki** [comment]
Ok, cool :)
